# Generated by Django 5.1.2 on 2024-10-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
