# Generated by Django 5.1.2 on 2024-10-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_rename_mensajes_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
